services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: rejonik
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+pymysql://root:@db/rejonik"
      SECRET_KEY: "${SECRET_KEY}"
    depends_on:
      - db


volumes:
  mysql_data: